# Xamarin.iOS

trigger:
- main

variables:
- group: 'variables'

jobs:
  - job: 'BuildiOS'
    pool:
      vmImage: 'macOS-latest'
    
    variables:
      buildConfiguration: 'Release'
    
    steps:
      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '**/*.sln'
      
      - task: DownloadSecureFile@1
        inputs:
          secureFile: '$(ProvisioningProfile-FileName)'
      
      - task: DownloadSecureFile@1
        inputs:
          secureFile: '$(AppleCertificate-FileName)'
      
      - task: InstallAppleCertificate@2
        inputs:
          certSecureFile: '$(AppleCertificate-FileName)'
          certPwd: '$(AppleCertificate-Password)'
      
      - task: InstallAppleProvisioningProfile@1
        inputs:
          provisioningProfileLocation: secureFiles
          provProfileSecureFile: '$(ProvisioningProfile-FileName)'
          removeProfile: true

      - task: XamariniOS@2
        inputs:
          solutionFile: '**/*.sln'
          configuration: '$(buildConfiguration)'
          buildForSimulator: false
          packageApp: true
          signingIdentity: $(APPLE_CERTIFICATE_SIGNING_IDENTITY)
          signingProvisioningProfileID: $(APPLE_PROV_PROFILE_UUID)
      
      - task: CopyFiles@2
        inputs:
          Contents: '**/*.ipa'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          OverWrite: true
          flattenFolders: true
      
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'MyAwesomeApp-$(Build.BuildNumber)'
          publishLocation: Container