trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'

steps:
  # Step 1: Checkout Code
  - checkout: self

  # Step 2: Install Dependencies
  - script: |
      brew update
      brew install mono
      brew install --cask xamarin-android
      brew install --cask xamarin-ios
    displayName: 'Install Dependencies'

  # Step 3: Restore NuGet Packages with MSBuild
  - task: MSBuild@1
    displayName: 'Restore NuGet Packages'
    inputs:
      solution: '**/*.sln'
      msbuildArguments: '/restore'

  # Step 4: Build Android Project
  - task: MSBuild@1
    displayName: 'Build Xamarin.Android'
    inputs:
      solution: '**/*Droid*.csproj'
      configuration: $(buildConfiguration)
      msbuildArguments: '/t:SignAndroidPackage'

  # Step 5: Build iOS Project
  - task: MSBuild@1
    displayName: 'Build Xamarin.iOS'
    inputs:
      solution: '**/*.iOS.csproj'
      configuration: $(buildConfiguration)
      msbuildArguments: '/t:Build'

  # Step 6: Publish Build Artifacts
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Build Artifacts'
    inputs:
      pathtoPublish: '**/bin/Release'
      artifactName: 'drop'
