name: Build Xamarin.iOS app

on: [push]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.405'
    
    - name: Install Xamarin dependencies
      run: |
          brew update
          brew install --cask xamarin-ios
          brew install --cask xamarin-android

    - name: Install dependencies
      run: nuget restore XamarinPiplineTest.sln

    - name: Debug generation
      run: |
        msbuild XamarinPiplineTest/XamarinPiplineTest.iOS/XamarinPiplineTest.iOS.csproj /t:Rebuild \
          /p:Configuration=Debug \
          /p:Platform=iPhoneSimulator \
          /p:BuildIpa=true \
          /p:SignAppleCertificate=false \
          /p:CodesignKeychain="" \
          /p:AppleCertificateSigningIdentity="" \
          /p:ProvisioningProfileUuid=""
